controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_login_check:
    path: /login_check
    controller: App\Controller\SecurityController::loginCheck

homepage:
    path: /
    controller: App\Controller\HomeController::index